name: Build and Publish the docker image to docker hub
on:
  push:
    branches:
      - main
jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build ./ -t rajanfac/user-manager-build:latest

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push the Docker image
        run: docker push rajanfac/user-manager-build:latest